import { useEffect, useState } from 'react'
import { studioRequest } from '@/services/studio-api'
type Source = { id: string; industry: string; evidence: { title: string; url: string; excerpt: string; limitations?: string[] }; reviewStatus: string; revision: number }
export function StudioLibrary({ industry, selected, onSelect }: { industry: string; selected: string[]; onSelect: (ids: string[]) => void }) {
  const [sources, setSources] = useState<Source[]>([])
  const [url, setUrl] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  useEffect(() => { let active = true; studioRequest<{ sources: Source[] }>('/library/sources').then(data => { if (active) setSources(data.sources) }).catch(cause => { if (active) setError(cause instanceof Error ? cause.message : 'Library could not load.') }); return () => { active = false } }, [])
  async function run(action: () => Promise<void>) { setBusy(true); setError(''); try { await action() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Source request failed.') } finally { setBusy(false) } }
  return <section className="studio-panel"><h2>Industry source library</h2><p>Save references, inspect the captured evidence, then approve the sources you want to reuse. Approval is your editorial decision.</p>{error && <p role="alert">{error}</p>}<form onSubmit={event => { event.preventDefault(); void run(async () => { const source = await studioRequest<Source>('/library/sources', { url, industry }, 'POST'); setSources(previous => [source, ...previous.filter(entry => entry.id !== source.id)]); setUrl('') }) }}><label>Reference URL for {industry}<input type="url" required value={url} onChange={event => setUrl(event.target.value)} /></label><button disabled={busy}>Capture reference</button></form>{sources.map(source => <article className="studio-evidence" key={source.id}><h3><a href={source.evidence.url} target="_blank" rel="noreferrer">{source.evidence.title} ↗</a></h3><p>{source.industry} · {source.reviewStatus.replaceAll('_', ' ')}</p><details><summary>Inspect evidence</summary><blockquote>{source.evidence.excerpt}</blockquote>{source.evidence.limitations?.map((limit, index) => <p key={index}>{limit}</p>)}</details><div className="studio-toolbar">{source.reviewStatus !== 'approved' && <button disabled={busy} onClick={() => void run(async () => { const next = await studioRequest<Source>(`/library/sources/${source.id}`, { revision: source.revision, reviewStatus: 'approved' }, 'PATCH'); setSources(previous => previous.map(entry => entry.id === next.id ? next : entry)) })}>Approve reference</button>}{source.reviewStatus !== 'rejected' && <button disabled={busy} onClick={() => void run(async () => { const next = await studioRequest<Source>(`/library/sources/${source.id}`, { revision: source.revision, reviewStatus: 'rejected' }, 'PATCH'); setSources(previous => previous.map(entry => entry.id === next.id ? next : entry)); onSelect(selected.filter(id => id !== source.id)) })}>Reject</button>}</div>{source.reviewStatus === 'approved' && <label className="studio-check"><input type="checkbox" checked={selected.includes(source.id)} disabled={!selected.includes(source.id) && selected.length >= 5} onChange={event => onSelect(event.target.checked ? [...selected, source.id] : selected.filter(id => id !== source.id))} />Use in next package</label>}</article>)}{selected.length > 0 && <p>{selected.length} references selected. Preparing a package will use these instead of the single source above.</p>}</section>
}
