import { useEffect, useState } from 'react'
import { studioRequest } from '@/services/studio-api'
import { authHeaders } from '@/services/firebase'
type Kind = 'image' | 'audio' | 'video'
type Asset = { id: string; kind: Kind; status: string; error?: string; estimatedUsd?: number }
type MediaConfig = Record<Kind, { enabled: boolean; estimatedUsd: number | null }>
export function StudioMedia({ packageId, initialPrompt, script }: { packageId: string; initialPrompt: string; script: string }) {
  const [config, setConfig] = useState<MediaConfig | null>(null)
  const [assets, setAssets] = useState<Asset[]>([])
  const [kind, setKind] = useState<Kind>('image')
  const [prompt, setPrompt] = useState(initialPrompt)
  const [confirmed, setConfirmed] = useState(false)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [preview, setPreview] = useState<{ url: string; kind: Kind; id: string } | null>(null)
  useEffect(() => { let active = true; Promise.all([studioRequest<MediaConfig>('/media/config'), studioRequest<{ assets: Asset[] }>(`/packages/${packageId}/assets`)]).then(([settings, list]) => { if (active) { setConfig(settings); setAssets(list.assets) } }).catch(cause => { if (active) setError(cause instanceof Error ? cause.message : 'Media could not load.') }); return () => { active = false } }, [packageId])
  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview.url) }, [preview])
  async function run(action: () => Promise<void>) { setBusy(true); setError(''); try { await action() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Media request failed.') } finally { setBusy(false) } }
  return <section><h2>Generate production assets</h2><p>Create one asset at a time from your reviewed production prompts. Availability depends on the connected provider.</p>{error && <p role="alert">{error}</p>}<label>Asset type<select value={kind} disabled={busy} onChange={event => { setKind(event.target.value as Kind); setPrompt(event.target.value === 'audio' ? script.replace(/\[C\d+\]/g, '') : initialPrompt); setConfirmed(false) }}>{(['image', 'audio', 'video'] as const).map(value => <option key={value} value={value}>{value}{config && !config[value].enabled ? ' — unavailable' : ''}</option>)}</select></label><label>{kind === 'audio' ? 'Voiceover text' : 'Generation prompt'}<textarea minLength={10} maxLength={4000} value={prompt} disabled={busy} onChange={event => setPrompt(event.target.value)} /></label>{config?.[kind].enabled ? <><p>Estimated cost: ${Number(config[kind].estimatedUsd).toFixed(2)} USD per generation.</p><label className="studio-check"><input type="checkbox" checked={confirmed} disabled={busy} onChange={event => setConfirmed(event.target.checked)} />I approve the estimated cost for this generation.</label></> : <p className="studio-muted">{kind} generation is not configured. You can export the production prompts and use them in your own tool.</p>}<button disabled={busy || !confirmed || !prompt.trim() || !config?.[kind].enabled} onClick={() => void run(async () => { const asset = await studioRequest<Asset>(`/packages/${packageId}/assets`, { kind, prompt, requestId: crypto.randomUUID(), confirmCost: true }, 'POST'); setAssets(previous => [asset, ...previous.filter(entry => entry.id !== asset.id)]); setConfirmed(false) })}>{busy ? 'Processing…' : `Generate ${kind}`}</button><div className="studio-package-list">{assets.map(asset => <article key={asset.id} className="studio-evidence"><h3>{asset.kind} · {asset.status}</h3>{asset.error && <p role="alert">{asset.error}</p>}{asset.status === 'running' && <button disabled={busy} onClick={() => void run(async () => { const next = await studioRequest<Asset>(`/assets/${asset.id}/refresh`, {}, 'POST'); setAssets(previous => previous.map(entry => entry.id === asset.id ? next : entry)) })}>Check progress</button>}{asset.status === 'completed' && <button disabled={busy} onClick={() => void run(async () => { const response = await fetch(`/api/studio/assets/${asset.id}/file`, { headers: await authHeaders() }); if (!response.ok) throw new Error('Could not load the generated asset.'); setPreview({ url: URL.createObjectURL(await response.blob()), kind: asset.kind, id: asset.id }) })}>Preview and download</button>}</article>)}</div>{preview && <div className="studio-media-preview">{preview.kind === 'image' ? <img src={preview.url} alt="Generated production asset" /> : preview.kind === 'audio' ? <audio src={preview.url} controls /> : <video src={preview.url} controls />}<p><a href={preview.url} download={`asset-${preview.id}`}>Download asset</a></p></div>}</section>
}
