import { useEffect, useState } from 'react'
import { studioRequest, type StudioPackage } from '@/services/studio-api'
export function StudioHistory({ item, onRestore, disabled }: { item: StudioPackage; onRestore: (value: StudioPackage) => void; disabled: boolean }) {
  const [revisions, setRevisions] = useState<StudioPackage[]>([])
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  useEffect(() => { let active = true; studioRequest<{ revisions: StudioPackage[] }>(`/packages/${item.id}/history`).then(data => { if (active) setRevisions(data.revisions) }).catch(cause => { if (active) setError(cause instanceof Error ? cause.message : 'History could not load.') }); return () => { active = false } }, [item.id, item.revision])
  return <section><h2>Version history</h2><p>Restore an earlier content version as a new draft. Current evidence is retained and the restored draft needs review.</p>{error && <p role="alert">{error}</p>}{revisions.map(version => <details className="studio-evidence" key={version.revision}><summary>Revision {version.revision} · {version.editorialStatus.replaceAll('_', ' ')} · {new Date(version.updatedAt).toLocaleString()}</summary>{version.content ? <><h3>{version.content.website.title}</h3><p style={{ whiteSpace: 'pre-wrap' }}>{version.content.script}</p><details><summary>Full saved package</summary><pre style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{JSON.stringify(version.content, null, 2)}</pre></details><button disabled={busy || disabled || version.revision === item.revision} onClick={async () => { if (!window.confirm(`Restore content from revision ${version.revision}?`)) return; setBusy(true); setError(''); try { onRestore(await studioRequest<StudioPackage>(`/packages/${item.id}`, { revision: item.revision, content: version.content }, 'PATCH')) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Restore failed.') } finally { setBusy(false) } }}>Restore this content</button></> : <p>No generated content in this revision.</p>}</details>)}</section>
}
